sales_admin/lib/sales_admin_web/router.ex
defmodule SalesAdminWeb.Router do
  use SalesAdminWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SalesAdminWeb do
    pipe_through :browser


    post "/sales/legacy_import", SalesController, :process_legacy_import
    get "/sales/legacy_import", SalesController, :legacy_import
    get "/sales", SalesController, :index
    get "/", SalesController, :index
    #get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SalesAdminWeb do
  #   pipe_through :api
  # end
end

sales_admin/lib/sales_admin_web/controllers/sales_controller.ex
defmodule SalesAdminWeb.SalesController do
  use SalesAdminWeb, :controller
  import Ecto.Query

  def index(conn, _params) do
    render(conn, "index.html", total: get_total(), sales: get_legacy_sales())
  end

  defp get_legacy_sales() do
    q = from s in "legacy_view",
        select: [s.customer_name, s.item_description, s.item_price, s.quantity,
                 s.merchant_name, s.merchant_address]

    case SalesAdmin.Repo.all(q) do
      nil -> []
      result -> result
    end
  end

  defp get_total() do
    q = from o in SalesAdmin.OrderItem,
        select: sum(o.price * o.quantity)

    case SalesAdmin.Repo.one(q) do
      nil -> 0.0
      total -> total
    end
  end

  def legacy_import(conn, _params) do
    legacy_import = SalesAdmin.LegacyImport.changeset(%SalesAdmin.LegacyImport{})
    render(conn, "legacy_import.html", changeset: legacy_import)
  end

  def process_legacy_import(conn, params) do
      legacy_import = SalesAdmin.LegacyImport.changeset(%SalesAdmin.LegacyImport{})

    if upload = params["legacy_import"]["file_name"] do
      IO.inspect(upload)
      case SalesAdmin.LegacyImport.import(upload.path) do
        true ->
           redirect(conn, to: "/sales")
        {:error, message} -> 
          render(conn, "legacy_import.html", changeset: legacy_import, message: message)
      end
    else
      render(conn, "legacy_import.html", changeset: legacy_import, message: "You need to select a file.")
    end
  end

end

sales_admin/lib/sales_admin_web/views/sales_view.ex
defmodule SalesAdminWeb.SalesView do
  use SalesAdminWeb, :view
end

sales_admin/lib/sales_admin_web/templates/sales/index.html.eex
<h1>Current Sales: $<%= assigns[:total] %> </h1>

<%= if assigns[:message] do %>
<section class="row">
  <div class="alert alert-danger">
    <%= assigns[:message] %>
  </div>
</section>
<% end %>

<section class="row">
  <div class="column">
    <%= button("Legacy Import", to: "/sales/legacy_import", method: :get) %>
  </div>
</section>

<section class="row">
  <h2>Recent Sales</h2>
</section>

<section class="row">
  <table>
    <tr>
      <th>Customer Name</th>
      <th>Item Description</th>
      <th>Item Price</th>
      <th>Quantity</th>
      <th>Merchant Name</th>
      <th>Merchant Address</th>
    </tr>
    <%= for sale <- assigns[:sales] do %>
      <tr>
        <td><%= Enum.at(sale, 0)  %></td>
        <td><%= Enum.at(sale, 1)  %></td>
        <td><%= Enum.at(sale, 2)  %></td>
        <td><%= Enum.at(sale, 3)  %></td>
        <td><%= Enum.at(sale, 4)  %></td>
        <td><%= Enum.at(sale, 5)  %></td>
      </tr>
    <% end %>
  </table>
</section>

sales_admin/lib/sales_admin_web/templates/sales/legacy_import.html.eex
<section>
  <h2>Legacy Import System</h2>
</section>

<%= if assigns[:message] do %>
<section class="row">
  <div class="alert alert-danger">
    <%= assigns[:message] %>
  </div>
</section>
<% end %>

<section class="row">
  <%= form_for @changeset, Routes.sales_path(@conn, :process_legacy_import), [multipart: true] , fn form -> %>
    <label>
      File : <%=  file_input(form, :file_name) %>
    </label>
    
    <%= submit "Submit" %>

  <% end %>
</section>